on: push
name: deploy
jobs:
  build:
    name: build and push image
    runs-on: ubuntu-latest
    steps:
    - name: build and push to docker
    - uses: actions/checkout@v3
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ github.repository }}
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}